sonar.projectKey=eduprestamo
sonar.projectName=EduPrestamo
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.js,tests/**/*.spec.js
sonar.exclusions=node_modules/**,coverage/**,reports/**,data/**,**/*.test.js,**/*.spec.js
sonar.coverage.exclusions=src/server.js,src/seed.js,src/public/**

sonar.javascript.lcov.reportPaths=reports/coverage/lcov.info
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
